# the "amazon" Docker Hub namespace is only trusted for its "aws-lambda-*" images
# Noncompliant@+1 {{This image might run with "root" as the default user. Make sure it is safe here.}}
FROM amazon/aws-cli:2.15.0
