# Noncompliant@+1 {{This image runs with "root" or "containerAdministrator" as the default user. Make sure it is safe here.}}
FROM mcr.microsoft.com/dotnet/aspnet:8.0
ENTRYPOINT ["dotnet", "app.dll"]
