# "wolfi-base" defaults to root, unlike the rest of the chainguard catalog.
# Noncompliant@+1 {{This image might run with "root" as the default user. Make sure it is safe here.}}
FROM cgr.dev/chainguard/wolfi-base:latest
CMD ["id"]
